package main

import (
	"bufio"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

// TestEveryRegistryPathTheBackendTargetsIsARegisteredRoute is a sender/receiver
// drift guard across two repositories.
//
// The backend builds Registry URLs by hand (the contribution bridge posts to
// /api/v1/contribute, the ATC client to /internal/atc/issue). The Registry's
// route table lives in another repository, so nothing at compile time says
// whether a path a sender targets exists on the receiver. One sender did not:
// the community-intelligence push targeted /api/v1/aim/community-intelligence,
// which the Registry never registered, and every run was a silent 404 behind an
// org opt-in that promised otherwise.
//
// The receiver side is pinned in testdata/registry-routes.txt (generated by
// scripts/pin-registry-routes.py from the Registry's cmd/server/main.go, with
// the commit it was read at). This test walks the backend's non-test sources
// for Registry paths built onto a registry base URL and fails on any path the
// pin does not carry. Adding a sender means pinning the receiver's route first.
func TestEveryRegistryPathTheBackendTargetsIsARegisteredRoute(t *testing.T) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	backend := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
	pinPath := filepath.Join(backend, "testdata", "registry-routes.txt")

	pinned := map[string]bool{}
	f, err := os.Open(pinPath) //nolint:gosec // G304: path derived from runtime.Caller
	if err != nil {
		t.Fatalf("read the Registry route pin: %v (regenerate with scripts/pin-registry-routes.py)", err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) == 2 {
			pinned[parts[1]] = true
		}
	}
	if len(pinned) == 0 {
		t.Fatalf("the Registry route pin at %s is empty", pinPath)
	}

	// A Registry path: a string literal starting with /api/ or /internal/ that
	// sits in a file which also names a registry base URL. Path parameters in
	// the pin (":id") are matched segment by segment.
	pathLit := regexp.MustCompile(`"(/(?:api|internal)/[^"\s]*)"`)
	registryFile := regexp.MustCompile(`(?i)registryURL|RegistryURL|registryBase|REGISTRY_BRIDGE_URL|defaultRegistryURL`)

	var targets []struct{ file, path string }
	err = filepath.Walk(filepath.Join(backend, "internal"), func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
			return nil
		}
		src, err := os.ReadFile(p) //nolint:gosec // G304: walking the module's own sources
		if err != nil {
			return err
		}
		if !registryFile.Match(src) {
			return nil
		}
		for _, m := range pathLit.FindAllStringSubmatch(string(src), -1) {
			rel, _ := filepath.Rel(backend, p)
			targets = append(targets, struct{ file, path string }{rel, m[1]})
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk backend sources: %v", err)
	}
	if len(targets) == 0 {
		t.Fatal("no Registry path found in the backend sources; the sender scan is broken, not the senders")
	}

	for _, tg := range targets {
		if !matchesPinned(tg.path, pinned) {
			t.Errorf("%s targets %s, which the Registry does not register (pin: testdata/registry-routes.txt); a sender to a missing route is a silent 404", tg.file, tg.path)
		}
	}
}

// matchesPinned reports whether path equals a pinned route, treating a pinned
// ":param" segment as a wildcard for one segment.
func matchesPinned(path string, pinned map[string]bool) bool {
	if pinned[path] {
		return true
	}
	want := strings.Split(strings.TrimSuffix(path, "/"), "/")
	for p := range pinned {
		have := strings.Split(strings.TrimSuffix(p, "/"), "/")
		if len(have) != len(want) {
			continue
		}
		ok := true
		for i := range have {
			if have[i] != want[i] && !strings.HasPrefix(have[i], ":") {
				ok = false
				break
			}
		}
		if ok {
			return true
		}
	}
	return false
}
