#!/usr/bin/env bash
# Real-backend smoke for the AIM OTel wiring.
#
# Sibling to smoke-test.sh. That one verifies the OTel demo stack alone, end
# to end, with a synthetic OTLP signal generated by gen-signal.sh. This one
# verifies the next step: a live AIM backend, instrumented by
# internal/telemetry/Init, emits the fga.authorize parent span + per-step
# child tree when an HTTP client hits POST /api/v1/agents/<id>/authorize.
#
# Hermetic: this script does NOT touch the repo-root docker-compose, the
# user's running aim-backend / aim-postgres, or any persistent data. It
# brings up its own throwaway Postgres on an alt port, builds a fresh
# backend binary, runs it on an alt port, hits the endpoint, and tears
# everything down on exit.
#
# What this script does, in order:
#   1. Pre-flight: docker, curl, jq, go on PATH.
#   2. Boot a throwaway Postgres container (aim-smoke-postgres) on
#      $SMOKE_POSTGRES_PORT (default 55432). Wait on pg_isready.
#   3. Boot the OTel demo stack (collector + Tempo + Prometheus + Loki +
#      Grafana) by reusing the existing docker-compose.yml. Wait on /ready.
#   4. Build the backend binary and run it in the background on
#      $SMOKE_BACKEND_PORT (default 18080), pointing at the throwaway
#      Postgres + OTLP collector. Wait on /health.
#   5. Reset force_password_change=FALSE on the default admin (migration 013
#      ships the row with the flag set, which would block the public-login
#      flow even after ADMIN_PASSWORD rewrites the hash).
#   6. Login as admin, create an agent, POST /authorize, assert the body
#      shape (outcome present, not "ERROR").
#   7. Verify the trace lands in Tempo with span name fga.authorize plus at
#      least one fga.* child.
#   8. Tear down: kill backend, stop+rm throwaway Postgres, docker compose
#      down the OTel stack.
#
# Run from this directory:   ./smoke-backend.sh
#
# Exit codes:
#   0 = real-backend FGA span tree verified end to end
#   1 = pre-flight failure (missing tool)
#   2 = docker compose / docker run failed
#   3 = a service failed health check
#   4 = login / agent-create / authorize HTTP step failed
#   5 = trace did not land in Tempo or did not contain expected spans
#   6 = trace landed but is missing one or more of the 9 Slide 14 SemConv attrs
set -euo pipefail

cd "$(dirname "$0")"
DEMO_DIR="$(pwd)"
BACKEND_DIR="$(cd ../.. && pwd)"

# Load .env if present (port overrides for the OTel stack).
if [ -f .env ]; then
    # shellcheck disable=SC1091
    set -a; . ./.env; set +a
fi

OTEL_GRPC_PORT="${OTEL_GRPC_PORT:-4317}"
TEMPO_HTTP_PORT="${TEMPO_HTTP_PORT:-3200}"
PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
LOKI_PORT="${LOKI_PORT:-3100}"
GRAFANA_PORT="${GRAFANA_PORT:-3001}"

# Throwaway backend + Postgres on alt ports so the smoke does not collide
# with a user's long-running aim-backend / aim-postgres.
SMOKE_BACKEND_PORT="${SMOKE_BACKEND_PORT:-18080}"
SMOKE_POSTGRES_PORT="${SMOKE_POSTGRES_PORT:-55432}"
SMOKE_PG_CONTAINER="${SMOKE_PG_CONTAINER:-aim-smoke-postgres}"
SMOKE_PG_PASSWORD="${SMOKE_PG_PASSWORD:-smoke_postgres_password}"
SMOKE_PG_DB="${SMOKE_PG_DB:-identity}"

# These two flow into `docker run` arguments and the psql connection below.
# They default to safe constants but are env-overridable, so validate them
# against a strict allow-list before use — a value containing shell
# metacharacters or whitespace must never reach a command line. Fail closed on
# anything outside the pattern.
case "$SMOKE_PG_CONTAINER" in
    *[!A-Za-z0-9_.-]*|"")
        echo "FAIL: SMOKE_PG_CONTAINER must match [A-Za-z0-9_.-]+ (got '$SMOKE_PG_CONTAINER')"; exit 1 ;;
esac
case "$SMOKE_PG_DB" in
    *[!A-Za-z0-9_]*|"")
        echo "FAIL: SMOKE_PG_DB must match [A-Za-z0-9_]+ (got '$SMOKE_PG_DB')"; exit 1 ;;
esac

ADMIN_EMAIL="${ADMIN_EMAIL:-admin@opena2a.org}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-AIM2025!Smoke}"

# JWT signing material — backend exits at config.Validate() if missing.
# Generate per-run instead of hardcoding a placeholder so the file does
# not trip secret scanners (gitleaks jwt-secret-assignment rule). The
# value is ephemeral: lifetime is one smoke run against a throwaway
# Postgres container, then discarded.
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"

echo "==> AIM real-backend smoke (hermetic)"
echo "    Backend     : localhost:${SMOKE_BACKEND_PORT}"
echo "    Postgres    : localhost:${SMOKE_POSTGRES_PORT} (container ${SMOKE_PG_CONTAINER})"
echo "    OTLP gRPC   : localhost:${OTEL_GRPC_PORT}"
echo "    Tempo HTTP  : localhost:${TEMPO_HTTP_PORT}"

# 1. Pre-flight.
echo
echo "==> [1/8] Pre-flight"
# psql + pg_isready let us reach the throwaway Postgres over its published
# TCP port instead of `docker exec`-ing into the container. Talking to the
# published port keeps shell variables out of any docker exec argument list.
for tool in docker curl jq go psql pg_isready; do
    command -v "$tool" >/dev/null || { echo "FAIL: $tool not on PATH"; exit 1; }
done

# Cleanup function — installed BEFORE we start spinning up resources so that
# a fail-fast in a later step still tears things down cleanly.
BACKEND_PID=""
BACKEND_BIN="$DEMO_DIR/.smoke-backend.bin"
BACKEND_LOG="$DEMO_DIR/.smoke-backend.log"
cleanup() {
    if [ -n "${BACKEND_PID:-}" ] && kill -0 "$BACKEND_PID" 2>/dev/null; then
        kill "$BACKEND_PID" 2>/dev/null || true
        wait "$BACKEND_PID" 2>/dev/null || true
    fi
    rm -f "$BACKEND_BIN" "${BACKEND_BIN}.bootstrap"
    if [ "${KEEP_STACKS:-0}" != "1" ]; then
        docker compose down --remove-orphans >/dev/null 2>&1 || true
        docker rm -f "$SMOKE_PG_CONTAINER" >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT

# 2. Throwaway Postgres.
echo
echo "==> [2/8] Throwaway Postgres"
docker rm -f "$SMOKE_PG_CONTAINER" >/dev/null 2>&1 || true
docker run -d --name "$SMOKE_PG_CONTAINER" \
    -e POSTGRES_PASSWORD="$SMOKE_PG_PASSWORD" \
    -e POSTGRES_DB="$SMOKE_PG_DB" \
    -p "127.0.0.1:${SMOKE_POSTGRES_PORT}:5432" \
    timescale/timescaledb:latest-pg16 >/dev/null || { echo "FAIL: docker run postgres"; exit 2; }
attempt=0
while [ $attempt -lt 30 ]; do
    if pg_isready -h 127.0.0.1 -p "$SMOKE_POSTGRES_PORT" -U postgres -d "$SMOKE_PG_DB" >/dev/null 2>&1; then
        echo "    postgres ready"
        break
    fi
    attempt=$((attempt+1)); sleep 2
done
if [ $attempt -ge 30 ]; then
    echo "FAIL: throwaway postgres did not become ready"
    exit 3
fi

# 3. OTel demo stack.
echo
echo "==> [3/8] OTel demo stack"
docker compose down --remove-orphans >/dev/null 2>&1 || true
for c in aim-otel-collector aim-tempo aim-loki aim-prometheus aim-grafana; do
    docker rm -f "$c" >/dev/null 2>&1 || true
done
docker compose up -d 2>&1 | tail -5 || { echo "FAIL: otel stack compose up"; exit 2; }

wait_http() {
    local name="$1" url="$2" max=60 a=0
    while [ $a -lt $max ]; do
        if curl -sf "$url" >/dev/null 2>&1; then
            echo "    $name ready"
            return 0
        fi
        a=$((a+1)); sleep 2
    done
    echo "FAIL: $name not ready at $url"
    return 3
}
wait_http tempo      "http://localhost:${TEMPO_HTTP_PORT}/ready"   || exit 3
wait_http prometheus "http://localhost:${PROMETHEUS_PORT}/-/ready" || exit 3
wait_http loki       "http://localhost:${LOKI_PORT}/ready"         || exit 3
wait_http collector  "http://localhost:${OTEL_HEALTH_PORT:-13133}/" || exit 3

# 4. Backend.
echo
echo "==> [4/8] Build + run backend"
(
    cd "$BACKEND_DIR"
    go build -o "$BACKEND_BIN" ./cmd/server
    go build -o "${BACKEND_BIN}.bootstrap" ./cmd/bootstrap
)

# Run backend from $BACKEND_DIR — runMigrations() reads from the relative
# path "./migrations", so cwd must be apps/backend/ or the migrations table
# stays empty and the schema is never created.
(
    cd "$BACKEND_DIR"
    env \
        APP_PORT="$SMOKE_BACKEND_PORT" \
        ENVIRONMENT="development" \
        POSTGRES_HOST="localhost" \
        POSTGRES_PORT="$SMOKE_POSTGRES_PORT" \
        POSTGRES_USER="postgres" \
        POSTGRES_PASSWORD="$SMOKE_PG_PASSWORD" \
        POSTGRES_DB="$SMOKE_PG_DB" \
        POSTGRES_SSL_MODE="disable" \
        REDIS_HOST="" \
        JWT_SECRET="$JWT_SECRET" \
        ADMIN_EMAIL="$ADMIN_EMAIL" \
        ADMIN_PASSWORD="$ADMIN_PASSWORD" \
        OTEL_EXPORTER_OTLP_ENDPOINT="localhost:${OTEL_GRPC_PORT}" \
        "$BACKEND_BIN" >"$BACKEND_LOG" 2>&1 &
    echo $! > "$DEMO_DIR/.smoke-backend.pid"
)
BACKEND_PID="$(cat "$DEMO_DIR/.smoke-backend.pid")"
rm -f "$DEMO_DIR/.smoke-backend.pid"
echo "    backend pid=$BACKEND_PID, logs at $BACKEND_LOG"

# Wait for backend health. AIM /health returns service=agent-identity-management.
attempt=0
while [ $attempt -lt 60 ]; do
    if curl -sf "http://localhost:${SMOKE_BACKEND_PORT}/health" 2>/dev/null \
        | jq -e '.service == "agent-identity-management"' >/dev/null 2>&1; then
        echo "    backend ready"
        break
    fi
    if ! kill -0 "$BACKEND_PID" 2>/dev/null; then
        echo "FAIL: backend exited during boot"
        echo "--- last 60 lines of backend log ---"
        tail -60 "$BACKEND_LOG"
        exit 3
    fi
    attempt=$((attempt+1)); sleep 2
done
if [ $attempt -ge 60 ]; then
    echo "FAIL: backend not ready after 120s"
    tail -60 "$BACKEND_LOG"
    exit 3
fi

# 4b. Seed default admin via bootstrap binary.
#
# PR #141 (2cc5490, 2026-05-20) rewrote migration 013 to remove the hardcoded
# admin INSERT (CWE-798 fix; AIM Cloud's Azure Postgres does not allow-list
# pgcrypto, so SQL-side bcrypt is unavailable). The admin row is now seeded
# by aim-bootstrap --default after migrations run. Without this step the
# users table has no admin row and step 6 login returns 401.
#
# Idempotent: re-runs against an already-bootstrapped DB exit 0 with a "skip"
# message. Pass --admin-password so the login in step 6 matches ADMIN_PASSWORD.
echo
echo "==> [4b/8] Seed default admin via bootstrap"
(
    cd "$BACKEND_DIR"
    env \
        DATABASE_URL="postgres://postgres:${SMOKE_PG_PASSWORD}@localhost:${SMOKE_POSTGRES_PORT}/${SMOKE_PG_DB}?sslmode=disable" \
        "${BACKEND_BIN}.bootstrap" \
            --default \
            --admin-email="$ADMIN_EMAIL" \
            --admin-password="$ADMIN_PASSWORD" \
            --yes \
            >>"$BACKEND_LOG" 2>&1
) || { echo "FAIL: bootstrap --default did not seed admin"; tail -40 "$BACKEND_LOG"; exit 4; }
echo "    admin seeded"

# 5. Reset force_password_change.
echo
echo "==> [5/8] Reset admin force_password_change"
PGPASSWORD="$SMOKE_PG_PASSWORD" psql -h 127.0.0.1 -p "$SMOKE_POSTGRES_PORT" -U postgres -d "$SMOKE_PG_DB" -c \
    "UPDATE users SET force_password_change = FALSE WHERE email = '${ADMIN_EMAIL}';" >/dev/null

# 6. HTTP exercise.
echo
echo "==> [6/8] HTTP: login + create agent + authorize"
LOGIN_BODY=$(jq -n --arg e "$ADMIN_EMAIL" --arg p "$ADMIN_PASSWORD" '{email:$e, password:$p}')
TOKEN=$(curl -sf -X POST "http://localhost:${SMOKE_BACKEND_PORT}/api/v1/public/login" \
    -H "Content-Type: application/json" \
    -d "$LOGIN_BODY" | jq -r '.accessToken // empty')
if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
    echo "FAIL: admin login did not return accessToken"
    exit 4
fi
echo "    login OK"

AGENT_BODY=$(jq -n \
    --arg n "smoke-fga-agent-$(date +%s)" \
    '{name:$n, displayName:$n, agentType:"ai_agent", description:"smoke-backend.sh"}')
AGENT_ID=$(curl -sf -X POST "http://localhost:${SMOKE_BACKEND_PORT}/api/v1/agents" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$AGENT_BODY" | jq -r '.id // empty')
if [ -z "$AGENT_ID" ] || [ "$AGENT_ID" = "null" ]; then
    echo "FAIL: agent create did not return id"
    exit 4
fi
echo "    agent created id=${AGENT_ID}"

# Seed agent_security_contexts so agent.scan_verdict lands on the trace.
# In production this table is populated by the Registry ASC pipeline; in
# the smoke test the table doesn't exist yet, so create + populate it.
# The fga_engine reads it via fetchASCRiskSummary; missing rows fail open
# silently, which would let agent.scan_verdict drop off the parent span
# unnoticed and weaken the Slide 14 SemConv proposal credibility.
PGPASSWORD="$SMOKE_PG_PASSWORD" psql -h 127.0.0.1 -p "$SMOKE_POSTGRES_PORT" -U postgres -d "$SMOKE_PG_DB" -v ON_ERROR_STOP=1 -c \
    "CREATE TABLE IF NOT EXISTS agent_security_contexts (
        agent_id        UUID PRIMARY KEY,
        overall_risk    TEXT NOT NULL DEFAULT 'LOW',
        drift_score     DOUBLE PRECISION NOT NULL DEFAULT 0,
        active_alerts   INTEGER NOT NULL DEFAULT 0,
        atc_trust_level INTEGER NOT NULL DEFAULT 0,
        atx_trust_level INTEGER,
        scan_verdict    TEXT NOT NULL DEFAULT 'UNKNOWN'
     );" >/dev/null
PGPASSWORD="$SMOKE_PG_PASSWORD" psql -h 127.0.0.1 -p "$SMOKE_POSTGRES_PORT" -U postgres -d "$SMOKE_PG_DB" -v ON_ERROR_STOP=1 -c \
    "INSERT INTO agent_security_contexts (agent_id, overall_risk, drift_score, active_alerts, atc_trust_level, scan_verdict)
     VALUES ('${AGENT_ID}', 'LOW', 0.05, 0, 3, 'CLEAN')
     ON CONFLICT (agent_id) DO UPDATE SET scan_verdict='CLEAN';" >/dev/null
echo "    seeded agent_security_contexts row (scan_verdict=CLEAN)"

AUTH_BODY=$(jq -n '{capability:"file:read", resource:"/tmp/smoke", action:"read"}')
AUTH_RESP=$(curl -sf -X POST "http://localhost:${SMOKE_BACKEND_PORT}/api/v1/agents/${AGENT_ID}/authorize" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$AUTH_BODY")
OUTCOME=$(echo "$AUTH_RESP" | jq -r '.outcome // empty')
if [ -z "$OUTCOME" ]; then
    echo "FAIL: /authorize response missing outcome"
    echo "    response: $AUTH_RESP"
    exit 4
fi
if [ "$OUTCOME" = "ERROR" ]; then
    echo "FAIL: /authorize returned outcome=ERROR (engine infra failure)"
    echo "    response: $AUTH_RESP"
    exit 4
fi
echo "    /authorize outcome=${OUTCOME}"

# 7. Trace verification via Tempo TraceQL search.
# Filter by this run's agent.id so we never grab a stale trace from a
# previous smoke run (Tempo returns matching traces newest-first, but a
# tight retry loop can still hit a still-flushing slot before the new
# span lands; pinning to agent.id removes that race entirely).
echo
echo "==> [7/8] Verify fga.authorize trace landed in Tempo"
sleep 5  # batch span processor flush window
attempt=0
while [ $attempt -lt 15 ]; do
    resp=$(curl -sfG "http://localhost:${TEMPO_HTTP_PORT}/api/search" \
        --data-urlencode "q={ resource.service.name=\"aim-backend\" && name=\"fga.authorize\" && span.agent.id=\"${AGENT_ID}\" }" \
        --data-urlencode "limit=10" 2>/dev/null || true)
    if echo "$resp" | jq -e '.traces | length > 0' >/dev/null 2>&1; then
        TRACE_ID=$(echo "$resp" | jq -r '.traces[0].traceID')
        echo "    found trace_id=${TRACE_ID}"
        break
    fi
    attempt=$((attempt+1)); sleep 2
done
if [ -z "${TRACE_ID:-}" ]; then
    echo "FAIL: no fga.authorize trace from aim-backend in Tempo after 30s"
    echo "    last search response: $resp"
    exit 5
fi

TRACE=$(curl -sf "http://localhost:${TEMPO_HTTP_PORT}/api/traces/${TRACE_ID}" 2>/dev/null || true)
CHILD_COUNT=$(echo "$TRACE" | jq '
    [.batches[].scopeSpans[].spans[]
        | select(.name | startswith("fga.") and . != "fga.authorize")]
    | length' 2>/dev/null || echo 0)
if [ "${CHILD_COUNT:-0}" -lt 1 ]; then
    echo "FAIL: trace has no fga.* child spans (count=${CHILD_COUNT:-0})"
    exit 5
fi
echo "    trace has ${CHILD_COUNT} fga.* child span(s)"

# 7b. SemConv attribute coverage on the fga.authorize parent.
# The May 22 Slide 14 proposal locks 9 attribute names. fga_decision is a
# DENY here, so fga.denied_by must be present. fga.step lives on the per-step
# child spans (capability_check, attribute_check, ...), not on the parent.
# The remaining 8 must be on the parent.
echo
echo "==> [7b/8] Verify Slide 14 SemConv attrs on fga.authorize parent"
PARENT_ATTRS=$(echo "$TRACE" | jq -c '
    [.batches[].scopeSpans[].spans[]
        | select(.name == "fga.authorize")
        | .attributes[]
        | .key]' 2>/dev/null || echo '[]')
REQUIRED_SPAN_ATTRS=(
    "agent.id"
    "agent.public_key.algorithm"
    "agent.capability"
    "agent.trust_score"
    "agent.drift_score"
    "agent.scan_verdict"
    "agent.active_alerts"
    "fga.outcome"
    "fga.denied_by"
)
MISSING=()
for attr in "${REQUIRED_SPAN_ATTRS[@]}"; do
    if ! echo "$PARENT_ATTRS" | jq -e --arg a "$attr" 'index($a)' >/dev/null 2>&1; then
        MISSING+=("$attr")
    fi
done
if [ ${#MISSING[@]} -gt 0 ]; then
    echo "FAIL: fga.authorize span is missing required SemConv attrs:"
    for m in "${MISSING[@]}"; do echo "    - $m"; done
    echo "    present: $PARENT_ATTRS"
    exit 6
fi
echo "    all 9 required span attrs present on fga.authorize"

# 8. Done.
echo
echo "==> PASS: real-backend FGA span tree verified end to end"
echo "    outcome    : ${OUTCOME}"
echo "    trace_id   : ${TRACE_ID}"
echo "    children   : ${CHILD_COUNT}"
echo "    Tempo URL  : http://localhost:${GRAFANA_PORT}/explore?left=%7B%22datasource%22:%22tempo%22,%22queries%22:%5B%7B%22queryType%22:%22traceql%22,%22query%22:%22${TRACE_ID}%22%7D%5D%7D"
