#!/usr/bin/env bash
# gen-dev-secrets.sh — emit a .env block with fresh, locally-generated secrets
# for every required AIM env var.
#
# Usage:
#   ./scripts/gen-dev-secrets.sh > .env          # one-shot setup
#   eval "$(./scripts/gen-dev-secrets.sh export)" # load into current shell
#
# This helper exists because docker-compose.yml intentionally has no fallback
# defaults for secret-shaped env vars (CWE-798). Every operator generates their
# own values on first setup; production deployments override via the platform's
# secret-management system, not via this script.
#
# The backend (apps/backend/internal/config/config.go) rejects any value that
# matches a known development default in every environment, not only
# production, so even pasting a value you remember from another project will
# fail loudly at boot. Always regenerate.

set -euo pipefail

mode="${1:-env}"

if ! command -v openssl >/dev/null 2>&1; then
    echo "gen-dev-secrets.sh: openssl is required but not found in PATH" >&2
    exit 1
fi

# JWT_SECRET — HS256 signing key. >=32 chars required by Validate(); hex32 = 64.
jwt_secret="$(openssl rand -hex 32)"

# KEYVAULT_MASTER_KEY — base64-encoded 32 bytes for AES-256-GCM.
keyvault_master_key="$(openssl rand -base64 32)"

# POSTGRES_PASSWORD — base64, no padding noise for psql command lines.
postgres_password="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)"

# REDIS_PASSWORD — same shape as postgres.
redis_password="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)"

# MINIO_ROOT_PASSWORD — minio enforces >=8 chars; 32 is comfortable.
minio_root_password="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)"

# GRAFANA_ADMIN_PASSWORD — surfaced in a UI login, keep printable.
grafana_admin_password="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)"

prefix=""
if [[ "$mode" == "export" ]]; then
    prefix="export "
fi

cat <<EOF
# Generated by scripts/gen-dev-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit this file. Regenerate freely; values are not reused anywhere.
${prefix}JWT_SECRET=${jwt_secret}
${prefix}KEYVAULT_MASTER_KEY=${keyvault_master_key}
${prefix}POSTGRES_PASSWORD=${postgres_password}
${prefix}REDIS_PASSWORD=${redis_password}
${prefix}MINIO_ROOT_PASSWORD=${minio_root_password}
${prefix}GRAFANA_ADMIN_PASSWORD=${grafana_admin_password}
EOF
