#!/usr/bin/env bash
# sync-to-cloud.sh -- One-directional sync from agent-identity-management to aim-cloud
#
# Usage:
#   ./scripts/sync-to-cloud.sh <source-dir> <target-dir> [--dry-run]
#
# When run from the GitHub Action, source/target are checked-out paths.
# For local use:
#   ./scripts/sync-to-cloud.sh . ../aim-cloud
#   ./scripts/sync-to-cloud.sh . ../aim-cloud --dry-run

set -euo pipefail

# -- Arguments ----------------------------------------------------------------

SOURCE="${1:?Usage: sync-to-cloud.sh <source-dir> <target-dir> [--dry-run]}"
TARGET="${2:?Usage: sync-to-cloud.sh <source-dir> <target-dir> [--dry-run]}"
DRY_RUN=false

for arg in "${@:3}"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown flag: $arg"; exit 1 ;;
  esac
done

SOURCE="$(cd "$SOURCE" && pwd)"
TARGET="$(cd "$TARGET" && pwd)"

# -- Import paths --------------------------------------------------------------

SRC_IMPORT="github.com/opena2a-org/agent-identity-management/apps/backend/internal/"
DST_IMPORT="github.com/opena2a/identity/backend/internal/"

# -- Protected files manifest --------------------------------------------------
# Read from aim-cloud/.sync-protect if it exists, otherwise use built-in list.

PROTECT_FILE="$TARGET/.sync-protect"
PROTECTED_PATTERNS=()

load_protected_patterns() {
  if [[ -f "$PROTECT_FILE" ]]; then
    while IFS= read -r line; do
      # Skip comments and blank lines
      [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
      PROTECTED_PATTERNS+=("$line")
    done < "$PROTECT_FILE"
  else
    # Fallback built-in list
    PROTECTED_PATTERNS=(
      "apps/backend/cmd/server/main.go"
      "apps/backend/internal/infrastructure/stripe/"
      "apps/web/app/auth/login/page.tsx"
      "apps/web/app/auth/google/"
      "apps/web/app/auth/callback/"
      "apps/web/app/auth/error/"
      "apps/web/app/settings/"
      "apps/web/app/onboarding/"
      "apps/web/app/get-started/"
      "apps/web/app/terms/"
      "apps/web/app/privacy/"
      "apps/web/app/device/"
      "apps/web/lib/api.ts"
      "apps/web/hooks/use-plan-usage.ts"
      "apps/web/proxy.ts"
      "apps/web/components/dashboard/sidebar.tsx"
    )
  fi
}

load_protected_patterns

# -- Scratch space -------------------------------------------------------------
# One temp dir for the whole run, removed on any exit path including the `set -e`
# abort inside a mirror.

SYNC_TMPDIR="$(mktemp -d)"
trap 'rm -rf "$SYNC_TMPDIR"' EXIT

# -- Counters ------------------------------------------------------------------

ADDED=0
MODIFIED=0
SKIPPED=0
IMPORT_REWRITES=0

# -- Helpers -------------------------------------------------------------------

is_protected() {
  local relpath="$1"
  for pattern in "${PROTECTED_PATTERNS[@]}"; do
    # Exact file match
    if [[ "$relpath" == "$pattern" ]]; then
      return 0
    fi
    # Directory prefix match (pattern ends with /)
    if [[ "$pattern" == */ && "$relpath" == "$pattern"* ]]; then
      return 0
    fi
    # Stripe path check
    if [[ "$relpath" == *"/stripe/"* ]]; then
      return 0
    fi
  done
  return 1
}

log_info() {
  echo "[SYNC] $*"
}

log_skip() {
  echo "[SKIP] $*"
  SKIPPED=$((SKIPPED + 1))
}

log_dry() {
  echo "[DRY ] $*"
}

# -- Protected mirroring -------------------------------------------------------
#
# The per-file sync loops call is_protected() on every candidate. The whole-tree
# mirrors (`rsync -a --delete`) did not, so a .sync-protect entry under one of
# them was silently ineffective in BOTH directions: the file was overwritten by
# public's version, and -- worse -- a cloud-only file there was deleted outright.
#
# The fix is an exclude list, because rsync's `--delete` does not remove files
# the filter excluded (that would need `--delete-excluded`, which is never
# passed). So one `-` rule per protected path both withholds the copy and
# prevents the deletion.
#
# The list is generated by running is_protected() over the union of the source
# and destination trees rather than by re-parsing .sync-protect. That matters:
# a second parser would be a second set of matching rules to keep in step, and
# the failure mode of drift here is silent data loss. Enumerating the
# destination too is what protects a cloud-only file, which by definition has no
# source path to match.

# A protected path becomes an rsync pattern, and rsync patterns have wildcards.
# A file literally named `report[1].json` would be read as a character class and
# protect the wrong set -- silently, in a security control. So escape every
# metacharacter and emit NUL-terminated rules (`--from0`), which also removes the
# two line-oriented hazards: a filename containing a newline splitting into two
# bogus rules, and a leading `#` or `;` being read as a comment.
#
# Neither tree has such a filename today. That is why this is worth doing now:
# the failure mode is a protected file that quietly stops being protected, and
# nothing would report it.
escape_rsync_pattern() {
  local s="$1"
  s="${s//\\/\\\\}"   # backslash first, or it re-escapes the escapes below
  s="${s//\[/\\[}"
  s="${s//\]/\\]}"
  s="${s//\*/\\*}"
  s="${s//\?/\\?}"
  printf '%s' "$s"
}

# build_rsync_excludes <rel_prefix> <src_dir> <dst_dir> <out_file>
# Writes NUL-terminated anchored rsync exclude patterns, relative to the transfer
# root, for every path under <rel_prefix> that is_protected() would skip.
# Echoes the count.
build_rsync_excludes() {
  local rel_prefix="$1" src_dir="$2" dst_dir="$3" out_file="$4"

  : > "$out_file"

  {
    local dir f rel
    for dir in "$src_dir" "$dst_dir"; do
      [[ -d "$dir" ]] || continue
      while IFS= read -r -d '' f; do
        rel="${f#"$dir/"}"
        if is_protected "$rel_prefix/$rel"; then
          # Leading slash anchors the pattern to the transfer root, so
          # `lib/api.ts` cannot be matched by an unrelated nested `lib/api.ts`.
          printf '/%s\0' "$(escape_rsync_pattern "$rel")"
        fi
      done < <(find "$dir" -type f -print0)
    done
  } | LC_ALL=C sort -z -u > "$out_file"

  tr -cd '\0' < "$out_file" | wc -c | tr -d ' '
}

# sdk/ alone removes ~900 stale build artifacts per run, so listing every path
# would bury the handful that matter. The summary line always carries the exact
# total; only the enumeration is capped, and the cap announces itself. A
# truncated list that does not admit it was truncated reads as a complete one.
DELETE_LOG_CAP=25

# list_deletions <log_fn> <rel_prefix> <itemize_output_file>
list_deletions() {
  local log_fn="$1" rel_prefix="$2" file="$3"
  local shown=0 total=0 rel
  while IFS= read -r rel; do
    total=$((total + 1))
    if (( shown < DELETE_LOG_CAP )); then
      "$log_fn" "DELETE $rel_prefix/$rel"
      shown=$((shown + 1))
    fi
  done < <(sed -n 's/^\*deleting  *//p' "$file")
  if (( total > shown )); then
    "$log_fn" "DELETE ...and $((total - shown)) more under $rel_prefix/ (not listed)"
  fi
}

# count_deletions <itemize_output_file>
count_deletions() {
  sed -n 's/^\*deleting  *//p' "$1" | wc -l | tr -d ' '
}

# mirror_protected <rel_prefix> <src_dir> <dst_dir> [extra rsync args...]
# `rsync -a --delete` that honours .sync-protect, and that says what it deleted.
# Silence was half the defect: the previous version logged one SYNCED line
# whether it copied nothing or removed a directory's worth of cloud-only files.
mirror_protected() {
  local rel_prefix="$1" src_dir="$2" dst_dir="$3"
  shift 3

  # Named under the script-level temp dir rather than mktemp'd per call: `set -e`
  # means a failing rsync never returns here, and a RETURN trap would outlive the
  # function and then fire against unset locals under `set -u`. The EXIT trap on
  # SYNC_TMPDIR covers every path out.
  local slug="${rel_prefix//\//_}"
  local excl_file="$SYNC_TMPDIR/excl.$slug"
  local out_file="$SYNC_TMPDIR/itemize.$slug"

  local protected_count
  protected_count="$(build_rsync_excludes "$rel_prefix" "$src_dir" "$dst_dir" "$excl_file")"

  local rel
  while IFS= read -r -d '' rel; do
    log_skip "$rel_prefix${rel} (protected)"
  done < "$excl_file"

  local deletions
  if $DRY_RUN; then
    rsync -a --delete --dry-run --itemize-changes --from0 \
      --exclude-from="$excl_file" "$@" "$src_dir/" "$dst_dir/" > "$out_file" || true
    deletions="$(count_deletions "$out_file")"
    list_deletions log_dry "$rel_prefix" "$out_file"
    log_dry "SYNC   $rel_prefix/ ($deletions deletion(s), $protected_count protected)"
  else
    mkdir -p "$dst_dir"
    rsync -a --delete --itemize-changes --from0 \
      --exclude-from="$excl_file" "$@" "$src_dir/" "$dst_dir/" > "$out_file"
    deletions="$(count_deletions "$out_file")"
    list_deletions log_info "$rel_prefix" "$out_file"
    log_info "SYNCED $rel_prefix/ ($deletions deletion(s), $protected_count protected)"
  fi
}

# -- Backend sync --------------------------------------------------------------

sync_backend() {
  log_info "--- Backend Go files ---"

  local src_backend="$SOURCE/apps/backend"
  local dst_backend="$TARGET/apps/backend"

  if [[ ! -d "$src_backend" ]]; then
    log_info "No backend directory in source, skipping"
    return
  fi

  # Find all Go files in source backend
  while IFS= read -r -d '' src_file; do
    local relpath="${src_file#"$SOURCE/"}"
    local dst_file="$TARGET/$relpath"

    if is_protected "$relpath"; then
      log_skip "$relpath (protected)"
      continue
    fi

    if $DRY_RUN; then
      if [[ -f "$dst_file" ]]; then
        log_dry "MODIFY $relpath"
      else
        log_dry "ADD    $relpath"
      fi
      continue
    fi

    # Ensure target directory exists
    mkdir -p "$(dirname "$dst_file")"

    if [[ -f "$dst_file" ]]; then
      # Copy and check if content changed
      local old_hash new_hash
      old_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
      cp "$src_file" "$dst_file"
      new_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
      if [[ "$old_hash" != "$new_hash" ]]; then
        log_info "MODIFY $relpath"
        MODIFIED=$((MODIFIED + 1))
      fi
    else
      cp "$src_file" "$dst_file"
      log_info "ADD    $relpath"
      ADDED=$((ADDED + 1))
    fi
  done < <(find "$src_backend" -name '*.go' -print0)

  # Also sync non-Go backend files that matter: schema, scripts, seed, tests
  for subdir in schema scripts seed tests; do
    local src_sub="$src_backend/$subdir"
    local dst_sub="$dst_backend/$subdir"
    if [[ -d "$src_sub" ]]; then
      mirror_protected "apps/backend/$subdir" "$src_sub" "$dst_sub"
    fi
  done
}

# -- Import path rewriting ----------------------------------------------------

rewrite_imports() {
  log_info "--- Rewriting Go import paths ---"

  local dst_backend="$TARGET/apps/backend"

  if [[ ! -d "$dst_backend" ]]; then
    return
  fi

  if $DRY_RUN; then
    local count
    count=$(grep -rl "$SRC_IMPORT" "$dst_backend" --include='*.go' 2>/dev/null | wc -l | tr -d ' ' || true)
    log_dry "Would rewrite imports in $count files"
    return
  fi

  while IFS= read -r -d '' gofile; do
    if grep -q "$SRC_IMPORT" "$gofile" 2>/dev/null; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|${SRC_IMPORT}|${DST_IMPORT}|g" "$gofile"
      else
        sed -i "s|${SRC_IMPORT}|${DST_IMPORT}|g" "$gofile"
      fi
      IMPORT_REWRITES=$((IMPORT_REWRITES + 1))
    fi
  done < <(find "$dst_backend" -name '*.go' -print0)

  log_info "Rewrote imports in $IMPORT_REWRITES files"
}

# -- Frontend sync -------------------------------------------------------------

sync_frontend() {
  log_info "--- Frontend files ---"

  local src_web="$SOURCE/apps/web"
  local dst_web="$TARGET/apps/web"

  if [[ ! -d "$src_web" ]]; then
    log_info "No web directory in source, skipping"
    return
  fi

  # Sync specific frontend directories that are shared
  local shared_dirs=(
    "app/dashboard"
    "app/api"
    "app/auth/register"
    "app/auth/change-password"
    "app/auth/forgot-password"
    "app/auth/reset-password"
    "components"
    "lib"
    "hooks"
    "tests"
  )

  for dir in "${shared_dirs[@]}"; do
    local src_dir="$src_web/$dir"
    local dst_dir="$dst_web/$dir"

    if [[ ! -d "$src_dir" ]]; then
      continue
    fi

    # Sync files one at a time to respect protected patterns
    while IFS= read -r -d '' src_file; do
      local relpath="${src_file#"$SOURCE/"}"
      local dst_file="$TARGET/$relpath"

      if is_protected "$relpath"; then
        log_skip "$relpath (protected)"
        continue
      fi

      if $DRY_RUN; then
        if [[ -f "$dst_file" ]]; then
          log_dry "MODIFY $relpath"
        else
          log_dry "ADD    $relpath"
        fi
        continue
      fi

      mkdir -p "$(dirname "$dst_file")"

      if [[ -f "$dst_file" ]]; then
        local old_hash new_hash
        old_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
        cp "$src_file" "$dst_file"
        new_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
        if [[ "$old_hash" != "$new_hash" ]]; then
          log_info "MODIFY $relpath"
          MODIFIED=$((MODIFIED + 1))
        fi
      else
        cp "$src_file" "$dst_file"
        log_info "ADD    $relpath"
        ADDED=$((ADDED + 1))
      fi
    done < <(find "$src_dir" -type f \
      ! -name '*.d.ts' \
      ! -path '*/node_modules/*' \
      ! -path '*/.next/*' \
      -print0)
  done

  # Sync root-level config files (package.json is NOT synced -- deps differ)
  local root_files=(
    "tailwind.config.js"
    "postcss.config.js"
    "tsconfig.json"
    "eslint.config.mjs"
    "vitest.config.ts"
    "middleware.ts"
  )

  for f in "${root_files[@]}"; do
    local src_file="$src_web/$f"
    local dst_file="$dst_web/$f"
    local relpath="apps/web/$f"

    if [[ ! -f "$src_file" ]]; then
      continue
    fi

    if is_protected "$relpath"; then
      log_skip "$relpath (protected)"
      continue
    fi

    if $DRY_RUN; then
      log_dry "SYNC   $relpath"
      continue
    fi

    if [[ -f "$dst_file" ]]; then
      local old_hash new_hash
      old_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
      cp "$src_file" "$dst_file"
      new_hash=$(shasum -a 256 "$dst_file" | cut -d' ' -f1)
      if [[ "$old_hash" != "$new_hash" ]]; then
        log_info "MODIFY $relpath"
        MODIFIED=$((MODIFIED + 1))
      fi
    else
      cp "$src_file" "$dst_file"
      log_info "ADD    $relpath"
      ADDED=$((ADDED + 1))
    fi
  done
}

# -- Migrations sync (additive only) ------------------------------------------

sync_migrations() {
  log_info "--- Migrations (additive only) ---"

  local src_migrations="$SOURCE/apps/backend/migrations"
  local dst_migrations="$TARGET/apps/backend/migrations"

  if [[ ! -d "$src_migrations" ]]; then
    log_info "No migrations in source, skipping"
    return
  fi

  mkdir -p "$dst_migrations"

  for src_file in "$src_migrations"/*.sql; do
    [[ -f "$src_file" ]] || continue
    local fname
    fname=$(basename "$src_file")
    local dst_file="$dst_migrations/$fname"
    local relpath="apps/backend/migrations/$fname"

    # Respect .sync-protect: cloud pins some upstream migrations out of its tree
    # (renamed/renumbered duplicates, bring-up-only test data). The basename
    # guard below only skips identical filenames -- it misses a protected
    # migration that was renumbered in cloud, re-syncing a duplicate number.
    if is_protected "$relpath"; then
      log_skip "$relpath (protected)"
      continue
    fi

    if [[ -f "$dst_file" ]]; then
      # Already exists -- do not overwrite (migrations are immutable)
      continue
    fi

    if $DRY_RUN; then
      log_dry "ADD    apps/backend/migrations/$fname"
    else
      cp "$src_file" "$dst_file"
      log_info "ADD    apps/backend/migrations/$fname"
      ADDED=$((ADDED + 1))
    fi
  done
}

# -- SDK sync ------------------------------------------------------------------

sync_sdk() {
  log_info "--- SDK files ---"

  local src_sdk="$SOURCE/sdk"
  local dst_sdk="$TARGET/sdk"

  if [[ ! -d "$src_sdk" ]]; then
    log_info "No SDK directory in source, skipping"
    return
  fi

  # Same whole-tree mirror as the four backend subdirectories, and it had the
  # same bypass: nothing under sdk/ could be protected and cloud-only files
  # there were deleted. No .sync-protect entry lives under sdk/ today, which is
  # exactly why this is worth fixing now rather than after the first one does.
  mirror_protected "sdk" "$src_sdk" "$dst_sdk" \
    --exclude='node_modules' \
    --exclude='__pycache__' \
    --exclude='.venv'
}

# -- Dependency reconciliation -------------------------------------------------
# Public repo and aim-cloud keep independent go.mod files (`.sync-protect`-ed):
# public has AIM Secrets backends (cloud.google.com/secretmanager, Azure
# keyvault, HashiCorp vault, etc.); aim-cloud has Stripe. When the sync copies
# Go source that imports a dep public has added, aim-cloud's go.mod is missing
# it and `go build` reports `updates to go.mod needed`. Running `go mod tidy`
# in aim-cloud's tree pulls in the new transitive deps while keeping Stripe
# (because protected main.go + internal/infrastructure/stripe/ still reference
# it). Without this, every public dependency bump breaks the sync pipeline.

reconcile_go_deps() {
  if $DRY_RUN; then
    log_info "--- Dry run: skipping go mod tidy ---"
    return
  fi

  log_info "--- Reconciling aim-cloud go.mod with synced code ---"

  local dst_backend="$TARGET/apps/backend"

  if [[ ! -f "$dst_backend/go.mod" ]]; then
    log_info "No go.mod in target backend, skipping tidy"
    return
  fi

  if (cd "$dst_backend" && go mod tidy 2>&1); then
    log_info "go mod tidy: DONE"
  else
    echo ""
    echo "========================================="
    echo "go mod tidy FAILED -- aim-cloud cannot reconcile deps."
    echo "Likely cause: synced code imports a package public added but"
    echo "the module proxy cannot resolve from aim-cloud's module path."
    echo "========================================="
    exit 1
  fi
}

# -- Build verification --------------------------------------------------------

verify_build() {
  if $DRY_RUN; then
    log_info "--- Dry run: skipping build verification ---"
    return
  fi

  log_info "--- Verifying Go build ---"

  local dst_backend="$TARGET/apps/backend"

  if [[ ! -f "$dst_backend/go.mod" ]]; then
    log_info "No go.mod in target backend, skipping build check"
    return
  fi

  if (cd "$dst_backend" && go build ./... 2>&1); then
    log_info "Build verification: PASSED"
  else
    echo ""
    echo "========================================="
    echo "BUILD FAILED -- sync introduced errors."
    echo "Review the changes and fix before merging."
    echo "========================================="
    exit 1
  fi
}

# -- Main ----------------------------------------------------------------------

echo ""
echo "============================================"
if $DRY_RUN; then
  echo "  Sync Preview (DRY RUN)"
else
  echo "  Syncing agent-identity-management -> aim-cloud"
fi
echo "============================================"
echo "  Source: $SOURCE"
echo "  Target: $TARGET"
echo "  Protected patterns: ${#PROTECTED_PATTERNS[@]}"
echo "============================================"
echo ""

sync_backend
rewrite_imports
sync_frontend
sync_migrations
sync_sdk
reconcile_go_deps
verify_build

echo ""
echo "============================================"
echo "  Sync Summary"
echo "============================================"
echo "  Files added:     $ADDED"
echo "  Files modified:  $MODIFIED"
echo "  Files skipped:   $SKIPPED"
echo "  Import rewrites: $IMPORT_REWRITES"
if $DRY_RUN; then
  echo "  Mode: DRY RUN (no files changed)"
fi
echo "============================================"
echo ""
