#!/usr/bin/env bash
# test-sync-protect.sh -- .sync-protect must be honoured on EVERY path in
# sync-to-cloud.sh, not most of them.
#
# The per-file loops in sync_backend/sync_frontend consult is_protected(). The
# whole-tree mirrors (apps/backend/{schema,scripts,seed,tests} and sdk/) once did
# not, so an entry for a path under them was silently ineffective in both
# directions: public's version overwrote cloud's, and a cloud-only file was
# deleted by `rsync --delete`. Proven on 2026-08-12 -- aim-cloud PR #111 added
# apps/backend/tests/integration/verification_test.go to .sync-protect at
# 16:57:37Z and sync PR #112 still carried it at 17:03:53Z.
#
# The assertions come in pairs on purpose. "Protected file survives" alone is
# also satisfied by a sync that copies nothing, so each protected case is paired
# with an unprotected control that MUST be overwritten or deleted.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC="$SCRIPT_DIR/sync-to-cloud.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

SRC="$WORK/public"
DST="$WORK/cloud"

FAILURES=0

fail() {
  echo "  FAIL: $*"
  FAILURES=$((FAILURES + 1))
}

pass() {
  echo "  ok:   $*"
}

assert_file_contains() {
  local path="$1" want="$2" what="$3"
  if [[ ! -f "$path" ]]; then
    fail "$what -- file is missing entirely: ${path#"$DST/"}"
    return
  fi
  if grep -q "$want" "$path"; then
    pass "$what"
  else
    fail "$what -- ${path#"$DST/"} does not contain '$want'"
  fi
}

assert_absent() {
  local path="$1" what="$2"
  if [[ -e "$path" ]]; then
    fail "$what -- ${path#"$DST/"} still exists"
  else
    pass "$what"
  fi
}

# -- Fixture -------------------------------------------------------------------
# Every mirrored directory gets the same four cases:
#   shared-protected     both trees have it, cloud's content must win
#   shared-unprotected   both trees have it, public's content must win
#   cloudonly-protected  only cloud has it, it must survive --delete
#   cloudonly-plain      only cloud has it, --delete must remove it

MIRRORS=(
  "apps/backend/schema"
  "apps/backend/scripts"
  "apps/backend/seed"
  "apps/backend/tests"
  "sdk"
)

build_fixture() {
  rm -rf "$SRC" "$DST"
  local dir
  for dir in "${MIRRORS[@]}"; do
    mkdir -p "$SRC/$dir/nested" "$DST/$dir/nested"

    echo "PUBLIC_VERSION" > "$SRC/$dir/nested/shared-protected.txt"
    echo "CLOUD_VERSION"  > "$DST/$dir/nested/shared-protected.txt"

    echo "PUBLIC_VERSION" > "$SRC/$dir/nested/shared-unprotected.txt"
    echo "CLOUD_VERSION"  > "$DST/$dir/nested/shared-unprotected.txt"

    echo "CLOUD_ONLY"     > "$DST/$dir/nested/cloudonly-protected.txt"
    echo "CLOUD_ONLY"     > "$DST/$dir/nested/cloudonly-plain.txt"

    # A protected path becomes an rsync PATTERN, and rsync patterns have
    # wildcards. Without escaping, `report[1].json` is a character class matching
    # `report1.json` -- so the file it names goes unprotected while an unrelated
    # file is protected instead. Silent, and in a security control.
    echo "PUBLIC_VERSION" > "$SRC/$dir/nested/report[1].json"
    echo "CLOUD_VERSION"  > "$DST/$dir/nested/report[1].json"
    # The decoy is what makes it a real test: a character class would match this
    # name and protect the wrong file.
    echo "PUBLIC_VERSION" > "$SRC/$dir/nested/report1.json"
    echo "CLOUD_VERSION"  > "$DST/$dir/nested/report1.json"
  done

  # sync_backend's Go loop needs apps/backend to exist as a directory; give it
  # one real .go file so the rest of the script runs its normal course.
  mkdir -p "$SRC/apps/backend/internal"
  echo "package internal" > "$SRC/apps/backend/internal/doc.go"

  {
    echo "# generated by test-sync-protect.sh"
    for dir in "${MIRRORS[@]}"; do
      echo "$dir/nested/shared-protected.txt"
      echo "$dir/nested/cloudonly-protected.txt"
      echo "$dir/nested/report[1].json"
    done
  } > "$DST/.sync-protect"
}

# -- Run 1: dry run must not mutate the target --------------------------------

echo "== dry run leaves the target untouched =="
build_fixture
BEFORE="$(cd "$DST" && find . -type f -exec shasum -a 256 {} \; | LC_ALL=C sort)"
"$SYNC" "$SRC" "$DST" --dry-run > "$WORK/dryrun.log" 2>&1 || {
  echo "  FAIL: dry run exited non-zero"; sed 's/^/    /' "$WORK/dryrun.log"; exit 1
}
AFTER="$(cd "$DST" && find . -type f -exec shasum -a 256 {} \; | LC_ALL=C sort)"
if [[ "$BEFORE" == "$AFTER" ]]; then
  pass "dry run changed nothing on disk"
else
  fail "dry run modified the target tree"
fi

# The dry run must also SAY what it would delete. A preview that printed one
# SYNC line per directory is how the deletion half stayed invisible.
if grep -q 'DELETE .*cloudonly-plain.txt' "$WORK/dryrun.log"; then
  pass "dry run reports the deletions it would make"
else
  fail "dry run does not report deletions (grep 'DELETE .*cloudonly-plain.txt')"
fi

# -- Run 2: the real sync ------------------------------------------------------

echo
echo "== .sync-protect is honoured by every mirror =="
build_fixture
"$SYNC" "$SRC" "$DST" > "$WORK/sync.log" 2>&1 || {
  echo "  FAIL: sync exited non-zero"; sed 's/^/    /' "$WORK/sync.log"; exit 1
}

for dir in "${MIRRORS[@]}"; do
  echo "-- $dir/"
  # Protected: cloud's content survives, in both the shared and cloud-only case.
  assert_file_contains "$DST/$dir/nested/shared-protected.txt" \
    "CLOUD_VERSION" "$dir: protected shared file keeps cloud's content"
  assert_file_contains "$DST/$dir/nested/cloudonly-protected.txt" \
    "CLOUD_ONLY" "$dir: protected cloud-only file survives --delete"

  # Controls: without a protect entry the sync must still do its job, or the
  # two assertions above would pass on a script that syncs nothing at all.
  assert_file_contains "$DST/$dir/nested/shared-unprotected.txt" \
    "PUBLIC_VERSION" "$dir: unprotected shared file takes public's content"
  assert_absent "$DST/$dir/nested/cloudonly-plain.txt" \
    "$dir: unprotected cloud-only file is deleted"

  # Metacharacter pair: the protected name keeps cloud's content, and the decoy
  # that a character class WOULD have matched takes public's. Both assertions are
  # needed -- the first alone passes if escaping over-protects, the second alone
  # passes if it under-protects.
  assert_file_contains "$DST/$dir/nested/report[1].json" \
    "CLOUD_VERSION" "$dir: protected name with rsync metachars is honoured literally"
  assert_file_contains "$DST/$dir/nested/report1.json" \
    "PUBLIC_VERSION" "$dir: the decoy a character class would match is NOT protected"
done

echo
if (( FAILURES > 0 )); then
  echo "FAILED: $FAILURES assertion(s). .sync-protect is not effective everywhere."
  exit 1
fi
echo "PASSED: .sync-protect honoured on every sync path."
